export const PRODUCT_CATEGORIES = [
  "Laptops",
  "Electronics",
  "Fashion",
  "Accessories",
  "Headphones",
  "Books",
  "Footwear",
  "Smartphones",
  "Watches",
  "Cameras",
  "Home Kitchen",
  "Sports Outdoors",
  "Toys Games",
  "Automotive",
  "Health Wellness",
  "Groceries",
  "Beauty Personal Care",
  "Music Movies",
  "Garden Outdoors",
  "Pet Supplies",
  "Baby Products",
  "Food",
];
